apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
spec:
  type: ClusterIP # será criado ClusterIP, não exposto externamente.
  selector:
    app: prometheus
  ports:
  - port: 9090
    targetPort: 9090
