apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  type: ClusterIP # será criado ClusterIP, não exposto externamente. 
  selector:
    app: redis
  ports:
  - port: 6379
    targetPort: 6379
